apiVersion: v1
kind: Pod
metadata:
  name: kubectl
spec:
  automountServiceAccountToken: true
  serviceAccount: week4-sa
  containers:
  - command:
    - sleep
    - infinity
    image: bitnami/kubectl:latest
    name: kubectl

