apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: codns-cluster
  region: ap-northeast-2

nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
