#!/bin/bash

VENV_PATH=$(poetry env info -p 2>/dev/null)

if [[ -z "$VENV_PATH" ]]; then
    echo "Poetry virtual environment not found. Please ensure it's created."
    exit 1
fi

ACTIVATE_FILE="$VENV_PATH/bin/activate"

if [[ -f "$ACTIVATE_FILE" ]]; then
    echo "Activating virtual environment..."
    source "$ACTIVATE_FILE"
else
    echo "Activate file not found at $ACTIVATE_FILE."
    exit 1
fi